### ISSUE TITLE
Can not run on build

### ISSUE THREAD

**Issue by lukkinngai2462** [oshoham/UnityGoogleStreamingSpeechToText#2]
![image](https://user-images.githubusercontent.com/20396388/73421603-65618500-4361-11ea-8684-b79fd095a0f6.png)

When I run on the build. there is showing the error message, PlatformNotSupportException: Operation is not supported on this platform.

**Comment by Lemovision** [comment]
Maybe you can try to change in Player Settings > Api compatibility level > .NET 4.x

**Comment by oshoham** [comment]
Hi, thanks for opening this issue. @Lemovision is correct that you need to change the C# API compatibility level to .NET 4.x. I'll update the setup instructions accordingly. Sorry about that!
