### ISSUE TITLE
 StreamingAssets gcp_credentials not found with Android built

### ISSUE THREAD

**Issue by Lemovision** [oshoham/UnityGoogleStreamingSpeechToText#3]
I had this issue when building this for Android where gcp_credentials file can't be accessed
Eventually I solved this by adding this part in the code:
https://gist.github.com/amowu/8121334

Now the WWW is deprecated though and Unity recommend using UnityWebRequest apparently
Also the problem with this code is that it create a copy of gcp_credentials file in the file system,
so I suppose anyone could steal you credentials easily?

Could we have an update to this code to include an android fix with UnityWebRequest,
and if possible a solution that doesn't expose the gcp_credentials file?

**Comment by oshoham** [comment]
Hi, thanks for opening an issue. I haven't tested this library on Android or iOS and at this point I don't have any plans to, but I would gladly review a PR if you feel up to submitting one.

**Comment by Lemovision** [comment]
Ha I wish I could, but I have very limited understanding about csharp to be honest
I'm just using visual scripting in Unity with Bolt for that purpose at the moment
Anyway thanks for the great plugin, it helps a lot for my project
