### ISSUE TITLE
#Unity speechtotext

### ISSUE THREAD

**Issue by kartiknatekar** [oshoham/UnityGoogleStreamingSpeechToText#4]
InvalidOperationException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials

android platform  and attached this script to gameobject

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Google.Cloud.Speech.V1;
using System;

public class TestMicrophone : MonoBehaviour
{
    public string DEMO_FILE;
    // Start is called before the first frame update
    void Start()
    {
        string value = Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS");
        Debug.Log(value);
        var speech = SpeechClient.Create();
        var response = speech.Recognize(new RecognitionConfig()
        {
            Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
            SampleRateHertz = 16000,
            LanguageCode = "en",
        }, RecognitionAudio.FromFile(DEMO_FILE));
        foreach (var result in response.Results)
        {
            foreach (var alternative in result.Alternatives)
            {
                Debug.Log(alternative.Transcript);
            }
        }

    }

}

**Comment by oshoham** [comment]
Hi, as mentioned in the README, this library does not currently support Android, as I both don't have an Android device to test with and don't really have time to add additional features. Thanks for opening an issue, but please read the README before doing so in the future.
