### ISSUE TITLE
#Unity SpeechToText package load fail

### ISSUE THREAD

**Issue by LuminaNoxx** [oshoham/UnityGoogleStreamingSpeechToText#5]
Failed to resolve packages: The file [C:\Users\Username\New Unity Project\Packages\manifest.json] is not valid JSON:
  Unexpected token '}' at 8:9
          }
          ^. No packages loaded.

A re-import of the project may be required to fix the issue or a manual modification of C:/Users/Username/New Unity Project/Packages/manifest.json file.

The unexpected token is the lines that i needed to copy from your Installation description. 
I'm using Unity 2019.3.14f1 
I want to build an AR Android app using vuforia and using google's speech to text api, i followed all of your instructions but the package does not load. 
Any advice?

**Comment by oshoham** [comment]
Hi, this library is now hosted on [UPM](https://openupm.com/), so you should be able to install it in the future without having to directly modify your project's manifest.json.
